env:
  global:
    - secure: NQ4WFD2SAv+IECbMopRdP6O1/QTF7ijfdegIiHBQUwoxvhqUjbDN7xxBglx5ZB4rUSVpZCfgFT4GJ2UFdo+IBYtvsbHi4ggh2kxR6JxaM7c58pWpQh7A5cEnBnRHZG4+QLy6XiGmg1XNtFXP8oz5mx00JsQ8HUY5FghWj4IVPcZJS6QfHjhM/UPBG0R8K0mwDS+SyRniJ/pWgGnntwZzYiBvJBz0c3Ti1dMnvMCs4jBICI1tLRxKikhGcDG6rr/09zA/+389xS2foG8AkzUCV8t0tzN+2Mfudsxew4tDCy2ojdguAHR88tqhX0BaQLBfCAB+5DiBiPOZMfpG+5tPcvZNq6iGxJeRnTFXpiJUBxxqe/V3jKESz2WYRssIUgoir8+ZYh0++xOVdx5ttH7YQ7czP2PdJdgMU9ciDP8EyOtlFG8B8iKQtzUrriM2xioaJpraKR4T78SKFPCQgThPozzHYoEWnu5/HmB1E1oYw0ObEbJmjGp94zRaxApRJUp4JAOEijlBCoKr+Jj3tsZeuUOoVVVQUkVb16gyCxRfFDo7vYalgX6pDffXH/T47UdBUQLzsOv+P3O8ECXSXEoPk9TPEXqJZM4EWD8rvGKVyoJq8AeD7gfqeQCU/2WB+hS02ZeYr1/EtTd32+tzBAKYtR6ME8jKUzXPEO4ssQnU8aU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/repository-structure
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
