env:
  global:
    - secure: 0QvnT1WbhtRb0UUSfpaoT5iaIq3KGUlO/tHVmeRKa5rypX7NEN27qLn4TpmlUhMYgXCJJcatiMHoNn0kyWy8YV+SNNyK1F7kYqXwUJ266sidng+bikhi3giKs2Gj70Cs+C/pIAspN6fUCVHjuHokUBgA2kY4+2KeS/suHot+0CIWEDIj4EviKsBiWgRpBRJan+oJIoElHX5w0OzTg4RCQjoTp/BCcIFsEYZdv9H5EFRj0fw5C/nXtfBKYMuggmJFG5cQ/spyxO7zcSMdRZ9/5AG7Q2EJfADiP6nWOrtVlpxjIfzvEck8nfHV2qboEikBYn5/Wb8LtQG8YjoeLgNgeTy9gwe6bN0rQ7Zn8/osqO6bFSTyoay4aXdAVEJlj+bkn+Eoisg46GKlq89M5oJgFgMOI0UJNTYtqOw/XxXNwXj7XPp7Fw0jPl+8KP1Do+4XFT7hM0oXdza83DuHoYTs9kaeK+u8KPoKxQydCNsc7B+Q3JPpnuxLhalIRCE6z5IHpLca8kOkKFraohTdtzDEJlD07UwO57UECNa7DEWpDv4sFO+Bg1MqEU4ive+h2mwQ1WeW1gQs0/TClxfn7hh1VzvGB5KdfkeLmrjneGbQlHOEBuoKytRi/rRj3yC3B/d60cVsPXLqTdibNUysqjuetWHKzeNZUv1p/VtpFxBXyiI= 
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/repository-structure
    - GIT_BRANCH: master
    - UPDATE_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/repository-structure/master/update.py
    - ADMINISTATION_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/repository-structure/master/administration.py
    - DEBUG_PYFUNCEBLE_ON_SCREEN: YES
dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install ultimate-hosts-blacklist-input-repo-updater

script:
  - env
  - ultimate-hosts-blacklist-input-repo-updater --version
  - ultimate-hosts-blacklist-input-repo-updater -m

notifications:
  email:
    recipients:
      - dead-hosts@funilrys.com
      - mitchellkrogza+ultimatehostsblacklist@gmail.com
    on_success: never
    on_failure: always
